version: '3'

services:
  client_app:
    build: .
    env_file:
      - .env
    depends_on:
      - 'cassandra_db'
    links:
      - 'cassandra_db'
    ports: 
      - '8080:13337'

  cassandra_db:
    env_file:
      - cassandra.env
    image: cassandra:latest
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
